%% function fig = plotSolPrintable(sol, bagSol)

function fig = plotSolPrintable(sol, bagSol)
  nContours = 60;

  fig = figure( ...
            'paperunits', 'centimeters', ...
            'papersize', [18 10], ...
            'paperposition', [1 0.5 16 9], ...
            'outerposition', [0 0 0 0] ...
        );

        %{
  contour(sol.tg, sol.zg, sol.ug, ...
    linspace(min (0, prctile(sol.ug(:), 5) ), max(sol.ug(:)), nContours), ...
    'LineWidth', 1.5 ...
  );
  %}
  contour(sol.tg, sol.zg, sol.ug, ...
    prctile(sol.ug(:), 2:2:98), ...
    'LineWidth', 1.5 ...
  );

  %{
  hold on;
  contour(bagSol.tg, bagSol.zg, bagSol.ug, ...
    linspace(min (0, prctile(sol.ug(:), 5) ), max(sol.ug(:)), nContours), ...
    ':'     );
  hold off;
  %}
  % mesh(sol.tg, sol.zg, real(sol.ug));
  view(2); 
  colorbar('Location', 'SouthOutside'); 
  colormap jet;
  % title('u(z,t)');
  xlabel('t'); ylabel('z');
end

